# -------------------------------
# General window layout
# -------------------------------

general {
    layout = dwindle

    allow_tearing = false  # Allows `immediate` window rule to work

    gaps_in = 10
    gaps_out = 14
    border_size = 2
    col.inactive_border = $background
    col.active_border = $on_surface
    resize_on_border = true
}

dwindle {
    pseudotile = true
    preserve_split = true
    preserve_split = true
    smart_split = false
    smart_resizing = true
}
